/**
 * backend/agents/validator.js
 * 
 * Validator Agent Class
 * Independent safeguard that verifies the tone, payload structure, 
 * and safety of the generated feedback using a fast secondary model 
 * (Claude Haiku or Gemini fallback).
 */

import { SystemMessage, HumanMessage } from "@langchain/core/messages";
import { getPrimaryLLM, extractJSON, withRetry, runWithLogging } from "./utils.js";
import { VALIDATOR_SYSTEM_PROMPT, VALIDATOR_HUMAN_PROMPT } from "./prompts/validator.prompt.js";

export class ValidatorAgent {
    constructor() {
        this.llm = getPrimaryLLM();
    }

    /**
     * Executes the Validator agent.
     * @param {Object} input
     * @param {Object} input.feedbackPayload - The JSON string/object generated by the FeedbackAgent
     * @returns {Promise<Object>} The validated and potentially corrected feedback JSON
     */
    async run(input) {
        return await runWithLogging("ValidatorAgent", async () => {
            const rawFeedbackString = typeof input.feedbackPayload === "string" 
                ? input.feedbackPayload 
                : JSON.stringify(input.feedbackPayload, null, 2);

            const humanPrompt = VALIDATOR_HUMAN_PROMPT.replace("{feedbackInput}", rawFeedbackString);

            const messages = [
                new SystemMessage(VALIDATOR_SYSTEM_PROMPT),
                new HumanMessage(humanPrompt)
            ];

            // Execute LLM call with retry wrapper
            const response = await withRetry(async () => {
                const aiResponse = await this.llm.invoke(messages);
                const result = extractJSON(aiResponse.content);
                
                // Return the corrected version if invalid, else the original
                return result.isValid === false && result.correctedFeedback 
                    ? result.correctedFeedback 
                    : input.feedbackPayload;
            });

            return response;
        });
    }
}
